### ISSUE TITLE
3dplant wont transfer from Bridge

### ISSUE THREAD

**Issue by theGlaive** [aydinyanik/clarisse_survival_kit#10]
Hi. First of all thanks for all the hard work. It's an awesome set of tools.

Just started to play with it and encountered an issue when exporting any 3dplant from bridge won't bring them to Clarisse. Example would be Clovers **Plants_3d_rbDjZ_4K_3dplant_ms**
That with the megascan listener running obviously. As I tested a bunch of different assets from my bridge library and they worked nicely.

If I use import megascan library and select 3dplants only there it'll bring all the 3dplants no problem (without the models obviously as all of them are in fbx)

**Comment by aydinyanik** [comment]
Thank you for the first bug submission and the kind words! The bug has been fixed.

If you export a 3dplant asset via Bridge to a destination folder it only exports 1 LOD which gets the same structure as an atlas. So I made it fallback to atlas mode if it can't find the atlas/billboard textures.

By the way if you put obj/abc files inside the asset directories they will get imported automatically and materials will be assigned to them and shading rules will be created.

**Comment by theGlaive** [comment]
Also on one 3dplant asset in imported Translucency map for the atlas. Even though it's not connected to a shader it's fine. I can find a use for it. But for another 3dplant asset, it didn't bring Translucency for the atlas even though it was in a folder with the similar structure and naming conventions as a first asset.

**Comment by aydinyanik** [comment]
I fixed the Opacity bug. I will upload a new version once I have figured out why the normal import doesn't work anymore and why the translucency isn't assigned.
Never try to fix bugs while you're half asleep on Sunday morning.

**Comment by aydinyanik** [comment]
Hi @theGlaive I hopefully squashed the 2 bugs. I was accidentally overwriting the JSON files that the bridge was sending. Now I made a check to see if a JSON file already exists. If so it doesn't overwrite.

The translucency wasn't hooking because the default strength is 0. If it's 0 the attribute is locked. So I put it to 1 if you have a translucency map.

I can add cavity map support if you need it. Which blending mode operation should it use? What other things do you feel are missing?

**Comment by theGlaive** [comment]
Hey @aydinyanik 
Just tested it on Plants_3d_rhDso_4K_3dplant_ms
It did bring opacity map now just fine. But it didn't bring Translucency for the Atlas. It brought it only for the Billboard.

And in regards to a cavity map, it's like I suggested in my previous post: it may be multiplied on top of diffuse (blendtexture node or multiblend with mode multiply). The only thing is that it darkens original diffuse texture by quite a lot so I usually compensate that by brightening diffuse texture below a little bit with let's say Rescale Node and lowering Input Max a little bit. But it may be tricky for you to get a values right as different assets may need different values so it might be just wiser to set mix to 0 and let users decide how much cavity they want.

Also, you have that (Un)Stream Textures on a shelf there. Which nicely connect the new node and deletes the old one. But it would be nice to have this functionality enhanced a little bit. Let's say if it could besides all that scan the texture folder for tx textures with the same name when switching to stream and replace file path name as well. Because right now user would have to go through all the textures and change the file extension to tx manually.
And it would be nice to have a shelf button right to this one to batch convert files in selected texture nodes to tx format if needed if none are present in an asset folder.
I've noticed that if tx textures are present in the asset folder it bring them on the import instead of original bitmaps. Which is nice. But again (Un)Stream won't replace file path to a jpg texture for example.  It stays as tx even though texture node switched to regular.
And also it's kinda cool to have tx processing utility inside of Clarisse which could've worked by selecting a folder with textures on a hard drive or by selecting texture node inside of Clarisse to convert only those.

I didn't try all of the tools yet so at the moment those are my thought on the ones I've tried.

Thank you again for the effort!

**Comment by theGlaive** [comment]
Also, I've noticed quite interesting displacement offset number on the import. Like -0.11 or -0.22.
As far as I can see the majority of megascans displacements have middle point at 0.500 despite them being jpg or exr. So I think it might be better to set to -0.5 for the Front Offset as a default.

**Comment by aydinyanik** [comment]
Hi @theGlaive . I have tested it on 3 plant assets I have and with all 3 I get the translucency connected in both the atlas or billboard. Can you show me the filenames of the files in the atlas folder?

I can add a "add rescale" node script just as I have with blur/triplanar. So you can use it to rescale the levels of a texture like the diffuse.

I already have tx conversion planned and conversion to other image file formats. If I have some time I will finish it this week.

For displacement I have difficulty finding the center point. Once you start mixing materials and displacements it's hard to find the correct center point. From my tests I think -0.5 was too extreme. I'd love to have this working perfectly.

Kind regards,

Aydin

**Comment by theGlaive** [comment]
Hi @aydinyanik 
Thanks for the update. I did double checking and found the reason. The texture in the atlas folder had a name with Translucent in it. But it Billboard it was with Translucency. So I just changed it to Translucency in the Atlas and it worked. I think it an older asset. Need to redownload everything probably. Maybe it'll fix the naming on all older assets.

In regards of "add rescale: sounds like a plan!

To check the displacement texture center point I usally drop it in nuke and check the value outside the uv boarders. And then of course check it on & off on a render to see if a model keeps the same size and add just details. No balking up or squeezing down. Also you can check the white & black values of the image again in nuke with the automatic process. I forgot the node name though. Don't have Nuke with me at the moment.

Great new about tx converter. Can't wait for it.

**Comment by aydinyanik** [comment]
Hi @theGlaive ,

My script indeed didn't look for translucent. I will add that keyword to the list in a future update.
You can customize many of the settings to suit your needs.

By copying and modifying variables that exist in settings.py into user_settings.py(see the user folder location in the readme) you can modify the file matching rules to your need. Make sure you overwrite the whole FILENAME_MATCH_TEMPLATE variable from 'diffuse' to 'preview' and not 1 line.
[See this page for all the settings](https://github.com/aydinyanik/clarisse_survival_kit/blob/master/clarisse_survival_kit/settings.py#L6)

**Comment by aydinyanik** [comment]
@theGlaive you are right. I tested it out on certain assets and it worked. I must have been testing it on a wrongly setup displacement map before. I updated the script, fixed the mix and regular surface displacement offsets and also added the translucent keyword to the filename regex match template.

**Comment by theGlaive** [comment]
Plants are working fine now. Thanks for the update @aydinyanik 

One other thing (see screenshot):
![img-2019-02-05-19-58-09](https://user-images.githubusercontent.com/7063222/52320042-b1156480-2981-11e9-9aea-b3823eb8183c.png)
This is just an example asset. I've experienced the same issue with the rocks. So basically even though I've selected LOD0 in the bridge it brought everything and did a bunch of material instances for each LOD (it's only 1 reference geo on a screenshot but that's because I've converted to alembic only LOD0 for this asset so it brought only 1 geo). Is it possible to bring only the LOD selected in Bridge to not overflow the scene with unnecessary nodes? Or is it some reason to bring everything?

Also as you can see shading rules are misspelled. It should be ./*LOD0* not ./*LOD0 (you got it right with the plants - not sure why it brings some assets differently).

**Comment by aydinyanik** [comment]
The * is to catch everything from the start till the LOD text. Seems fine to me? Plants use the same rule setup.

For the LOD import my script currently import all 3d assets that are in the folder. If you don't want that you can export to a destination folder with the Bridge application. Unfortunately it will not move custom files you added like ABC. So it will only work on single items like rocks which are obj already. 

I will add a LOD selector in the Import Asset and Import Megascans Library script sometime in the future and read out which LOD bridge exports when it does the export. I haven't had the time to get there yet.

Cool idea about scattering. Definitely something I'd love to add.

**Comment by theGlaive** [comment]
Well, it didn't catch anything before I tweaked the rule. See screenshots (hope it helps):
![img-2019-02-06-08-43-04](https://user-images.githubusercontent.com/7063222/52357723-7d6f2480-29eb-11e9-9bb4-35c3d750eefc.png)
![img-2019-02-06-08-42-10](https://user-images.githubusercontent.com/7063222/52357730-8102ab80-29eb-11e9-97c1-2d9a41eee4d5.png)

Oh and by the way probably it could be a good idea to have double sided enabaled by default on all leaves-like, grass-like assets. Because I find myself constantly doing it on those manually after import. And a few times I missed a few and it rendered with one side black on a leaves. Thought I'm not sure how easy it's for the script to determine those particular assets. I bet they have some unique tags in json. Also enabling double sided on all materials wouldn't be a good idea of course.

**Comment by aydinyanik** [comment]
@theGlaive I wasn't behind my computer and was looking at the \* at the beginning instead of the end. I also think Github's markdown might have formatted your message with italics instead of showing the \*.

I fixed it. Sorry for the confusion. I also added the double sidedness to plants and atlases. Can you check if it works? I'm on 3.6 sp3 and I don't have access to v4 because my maintenance ran out.

**Comment by theGlaive** [comment]
> I also think Github's markdown might have formatted your message with italics instead of showing the *

You're right about that. That's funny.

I'll check the updated version after work. I'm in LA time zone.

**Comment by aydinyanik** [comment]
No problem. I forgot to mention that the default specular strength value is also configurable via the user_settings.py file. The variable is called DEFAULT_SPECULAR_STRENGTH and the default is 0.2, because another user was getting a strong white rim on other types of materials. I can set the Megascans assets to 1.0 strength (100%) if that's better.

**Comment by theGlaive** [comment]
> I can set the Megascans assets to 1.0 strength (100%) if that's better.

Yes please do. As Megascans textures have properly tweaked values for PBR shading.

**Comment by theGlaive** [comment]
Hey @aydinyanik 
Just installed and tested new update. All previously discussed things are fixed. Thank you.

The only thing I've noticed now is that for 3dplant displacement node isn't assigned in shading layer editor. Everything is there with proper -0.5 attributes and everything but just it isn't assigned. It's easy to do manually but you know, you did set up everything nicely for a one-click automatic solution so it would be a shame not to fix this little thing in the script.

At first, I thought you are not assigning disp on purpose but with it assigned the plants are so much better. It gives them additional volume and unevenness in shape so I think it should be enabled for sure.

**Comment by aydinyanik** [comment]
Hi @theGlaive ,

I made LOD0 by default use Displacement for plants/atlases. If you want other LODs to have displacement as well you can customize it via the user_settings.

Default:
ATLAS_LOD_DISPLACEMENT_LEVELS = [0]

If you want more you can change it like this:
ATLAS_LOD_DISPLACEMENT_LEVELS = [0, 1, 2]

**Comment by theGlaive** [comment]
Hi @aydinyanik 
Works great now. Thanks.

When are you planning to implement cavity import and blend like discussed before (Remap on a diffuse and cavity blend with multiply with 0 mix on top of it)?

**Comment by theGlaive** [comment]
Oh, and by the way, great job on texture converter/replacer. Works flawlessly! Fast and efficient! I even did once during render by mistake but it did it anyway on a fly. Blown away! Thank you.

One other thing I've noticed:
It's safer to enable Force Luminance for Single Channel File Behavior attribute on regular textures nodes for all the textures instead of adding Reorder with rrrr or enabling it only on Roughness maps. As I've encountered a few assets with single channel Specular maps for example. And right now Clarisse just shows them as black texture which isn't great.

**Comment by theGlaive** [comment]
One other thing:
Asset **_Scatter_Rock_qkbhX_8K_3d_ms_**
Even though I've selected 8K in Bridge it brought only Normal in 8K but all other texture in 4K.
Texture nodes have 8K in their names though.
And obviously, there are 8K textures in a folder with proper names.

Could you please look into that as well.

**Comment by aydinyanik** [comment]
Hi @theGlaive ,

Currently I don't have a resolution and LOD selector. The script just crawls the whole directory.
In a future update I will add these two.

Regarding specular being single channel. Unfortunately my script can't detect if an image is single channel or not, but if Megascans are all single channel by default I can make exclusions for that. Substance for example has sRGB specular maps.

I didn't make a .tx to * converter. .TX is a one way street unfortunately I think. I will add threading flags once I know how to get the thread count on a computer.

The other scripts/adjustments will be added when I get the time. My goal is to add the LOD and resolution picker improvements before my Megascans subscription runs out in March.

**Comment by theGlaive** [comment]
> Regarding specular being single channel. Unfortunately, my script can't detect if an image is a single channel or not, but if Megascans are all single channel by default I can make exclusions for that. Substance, for example, has sRGB specular maps.

Well, you didn't fully get what I've meant. A script doesn't need to detect Single Channel or not. Just set Force Luminance on texture nodes when script creates them and it's golden. As this attribute doesn't affect RGB textures at all, it would only affect Single Channel ones. To be on a safer side set Force Luminance on Displace, Bump, Specular, Roughness because they most commonly used as single channel ones. But most importantly don't add Reorder "rrr" after conversion to .tx as it's doesn't need that and will screw up RGB textures obviously.

**Comment by aydinyanik** [comment]
Streamed Map Files need a reorder node, because the Single Channel attribute is missing on TextureStreamedMapFiles. Some textures are saved as RGB and some only have a single channel. My script cannot know beforehand which files are single channel so I treat all files that are not sRGB as single channel files.

If you've found that some sRGB files get a reorder node please let me know, because my script should not add reorder nodes to those.

**Comment by aydinyanik** [comment]
@theGlaive could you test the new branch I have for LOD and Resolution improvements? Hopefully it should work much better. If you do find any errors could you send me a screenshot of the directory structure? It would help me a lot.

You can download the branch from [here](https://github.com/aydinyanik/clarisse_survival_kit/tree/dev-lod).

To install it please download the [.tar.gz file](https://github.com/aydinyanik/clarisse_survival_kit/blob/dev-lod/dist/clarisse_survival_kit-1.0.0.tar.gz) and follow Step 3 Option 2 from the readme. Make sure your command prompt is spawned in the folder where you downloaded the tar.gz file. In windows it's easy to spawn command prompt by holding Shift and clicking the right mouse button in a empty area in Windows Explorer, then click "Open command prompt window here" or "Open powershell window here".

**Comment by aydinyanik** [comment]
@theGlaive I added cavity map support with rescale node. I also added the rescale node to AO maps

**Comment by theGlaive** [comment]
Sorry was on a vacation. Gonna test soon updated stuff

**Comment by aydinyanik** [comment]
Hi @theGlaive ,

Welcome back. Hope you enjoyed your vacation.

I got some feedback regarding the rescale nodes on the diffuse texture. 
They also pointed me to the official guide from Quixel regarding map usage.
[Official usage guide](https://megascans.zendesk.com/hc/en-us/articles/115000612165-What-maps-are-included-and-how-do-I-use-them-)

Since AO maps need to be multiplied on top of the albedo/diffuse without rescaling the diffuse texture I will rollback these changes. Also for cavities. I will add a curve remap node in between the cavity node and the blend, but lightening the diffuse is not good practice according to the feedback I have received.

This week I will add some fixes and implement the changes. The official quixel guide also finally gave me information on the displacement strength I should use.
