### ISSUE TITLE
Installation problem - OS X

### ISSUE THREAD

**Issue by mzogithub** [aydinyanik/clarisse_survival_kit#13]
Hi, thanks for this set of scripts - it sounds awesome. Unfortunately, I was unable to make it work. My Python installation looks fine. CSK installation went smooth as well. All the files seem in the right place. The new tab appears, all the icons are there. When I click any of the icon I get errors like this one:

` 
Traceback (most recent call last):
00:10:08      File "<string>", line 1, in <module>
00:10:08    ImportError: No module named clarisse_survival_kit.settings`

I thought there was a path problem but the python paths but look fine, in fact it finds the icons and shows them. I'm on MacOS 10.13.6. Any idea how to solve this?

One anomaly I noticed is that I have two versions of Clarisse installed (3.6sp7 and 4.0b). CSK icons only appear on 3.6sp7, not on 4.0b). This was a secondary problem to me because my production version is 3.6sp7 but I thought to mention this anyway as this problem might be related to the error I get with 3.6sp7.

Many Thanks,
Maurizio

P.S.
Are you planning to implement workflow integration with the Disney Principled Shader as well since this has been added in 3.6sp7?

**Comment by ddesmond** [comment]
Hey Maurizio,
on osx there is a slight difference in setup. Please can you check your clarisse.env, and use that python path to install CSK. Opening command line and calling that version of python from that location should solve the issue (dont use just "python setup.py install" or only pip, you need to call or the full path to clarisse env python location or execute it from that folder).

Let us know if it works.

**Comment by aydinyanik** [comment]
@mzogithub ,

Also remove the shelf items before you reinstall it with the correct Python installation. They won't be updated because they already exist in the shelf. If you don't do that they will still point to the wrong Python installation.

**Comment by aydinyanik** [comment]
I forgot to answer your question related to the Disney shader. I don't have plans to support it for the following reasons:

- I don't have access to the version with the Disney shader. My maintenance ran out while I was on 3.6 sp3
- You can't blend the Disney shader using a PhysicalBlend material. The mix function requires the Standard material.

**Comment by mzogithub** [comment]
Thanks for getting back to me. Still nothing. I tried many things. My Python version in clarisse.env is 2.7 and it looks all fine. When I type `python --version` in terminal it returns `Python 2.7.15` which I believe is correct. I now have two python versions installed 2.7 and 3.7 but "Current" is still 2.7 (I also tried with only 2.7 installed but no difference). Clarisse seems to only work with 2.7 anyway. I removed all the shelf items each time before trying again. I went to the folder where CSK has been unzipped and - from within that folder - I ran `python setup.py install` and it seems all to work. The files are copied in `site-packages` within the correct Python installation folder `/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7`, however MacOS has two python folders in `/Library/Frameworks/Python.framework/Versions/2.7` and `/System/Library/Frameworks/Python.framework/Versions/2.7` and I read this is normal. What am I doing wrong? What did you exactly mean with "Opening command line and calling that version of python from that location"? You meant running the Python binary specifying the full path in terminal? I tried that but it didn't work but I probably didn't use the right syntax. I tried `/Library/Frameworks/Python.framework/Versions/2.7/Python /Applications/clarisse_survival_kit-master/setup.py install` Thanks again

**Comment by mzogithub** [comment]
I also wanted to add that I have just tried to add the scripts as shelf items manually, one by one, and when executed, they still return the same error as when installed with setup.py. Thanks

**Comment by aydinyanik** [comment]
Unfortunately I can't test on mac because I am on Windows. But are you sure you're using same Python executable that is defined in the clarisse.env file? If you open the env file it shows the path.
On Windows it shows:

> PYTHONHOME=C:\Python27

There may be a default Python installation folder you might have missed. Can you run the  following code with the script editor of Clarisse and copy paste the result the clarisse log window shows?

Script editor can be found in Windows -> Script Editor. Log can be found in Windows -> Log...

```
import sys
print sys.path
```

**Comment by mzogithub** [comment]
Thanks for the hint. This is what sys.path returns:

`['/private/var/folders/gf/t8bpcktj7ndg8pdtx7vbrqhm0000gn/T/AppTranslocation/0F1FFA81-2184-475E-87D0-9F148A175709/d/clarisse.app/Contents/MacOS/python',

'/private/var/folders/gf/t8bpcktj7ndg8pdtx7vbrqhm0000gn/T/AppTranslocation/0F1FFA81-2184-475E-87D0-9F148A175709/d/clarisse.app/Contents/MacOS',

'/private/var/folders/gf/t8bpcktj7ndg8pdtx7vbrqhm0000gn/T/AppTranslocation/0F1FFA81-2184-475E-87D0-9F148A175709/d/clarisse.app/Contents/MacOS',

'/private/var/folders/gf/t8bpcktj7ndg8pdtx7vbrqhm0000gn/T/AppTranslocation/0F1FFA81-2184-475E-87D0-9F148A175709/d/clarisse.app/Contents/MacOS',

'/Applications/Conductor.app/Contents/MacOS/python/lib/python2.7/site-packages',

'/Applications/Conductor.app/Contents/MacOS',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',

'/Library/Python/2.7/site-packages',

'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',

'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']
`

I believe Conductor app is messing things up. I don't need it and deleted it but Clarisse still looks for Python inside Conductor despite this path not being in clarisse.env. Is there any other place where I can edit where Clarisse looks for python other than Clarisse.env?

My clarisse.env looks like this:

`PYTHONHOME=/System/Library/Frameworks/Python.framework/Versions/2.7
PYTHONPATH=/System/Library/Frameworks/Python.framework/Versions/2.7/lib:$CLARISSE_BIN_DIR/python
ILISE_SERVER=LOCALHOST:40500
IX_SHELF_CONFIG_FILE=$CLARISSE_BIN_DIR/shelves/shelf.cfg
IX_SHELF_SCRIPT_PATH=
IX_SHELF_ICON_PATH=
IX_MENU_CONFIG_FILE=$CLARISSE_BIN_DIR/python/menus/init_menus.py
IX_MENU_SCRIPT_PATH=
IX_MENU_ICON_PATH=
IX_RESOLUTION_PRESET=`

Thanks again

**Comment by aydinyanik** [comment]
@mzogithub if you can locate the installation path of CSK inside the sitepackages folder you might be able to add the folder to the PYTHONPATH variable inside the clarisse.env file. Does this work? 

Like so(replace the path with the actual path):

`PYTHONPATH=/System/Library/Frameworks/Python.framework/Versions/2.7/lib:$CLARISSE_BIN_DIR/python:ADD_CSK_LOCATION_HERE`

On Windows the path locations are separated by a ; instead of a :

**Comment by ddesmond** [comment]
@mzogithub
Mac has diferent python setup for other reason i would not bother you with.
Clarisse relies to the System version builtin and compiled by apple.

For this to work you have to call the apple python. The best way to be sure is to go to that folder directly in bash shell and execute python there.

As shown in your env file you need to go here:
PYTHONHOME=/System/Library/Frameworks/Python.framework/Versions/2.7 PYTHONPATH=/System/Library/Frameworks/Python.framework/Versions/2.7/lib:$CLARISSE_BIN_DIR/python

This python you need to execute to install it properly. This is valid also if you update.

As your clarisse env files says, youre default python for clarisse is in /System not /library, which your defo python with which command shows. 

You sucesfully installed it cos you called "python" which points to your /library python.  But clarisse doesnt see that.
Yanik solutions may help you, but the best for you would be to locate your system python executable and run it from there. you can drag and drop setup.py to that window and install it as usual from bash.

If you need more halp just tag me.
Hope this clears a bit :)

**Comment by mzogithub** [comment]
@ddesmond @aydinyanik 

Hey guys, incredibly BOTH your solutions worked!

I was aware about python that ships with MacOS is located in /System/Library... and the custom installations in /Library.... However, I wrongly assumed that I only had the default 2.7 in System and 3.7 in Library. Actually, I had three installations of Python. The default 2.7 in System and both a custom 2.7 and a custom 3.7 in Library. My generic 'python' command in the shell was pointing to the custom 2.7 and not the system 2.7. While 'python3' points to the custom python 3.7 installation.

That being said, I confirmed this by doing the two different solutions for two different versions of Clarisse.

**First** I did Aydinyanik solution for Clarisse 4:

I installed the script with the shell "python" command. The script installed in the custom 2.7 installation of Python, the one in Library. At this stage, of course, it still didn't work.

Then I added /Library/Frameworks/Python.framework/Versions/2.7/lib to PYTHONPATH, leaving in also the path to the System installation of python. Now the script works in Clarisse 4 only.

**Second** I did Ddesmond solution for Clarisse 3.6

I located the binary of the System 2.7 Python.

I went to the directory where I uncompressed the script: `cd /Applications/clarisse_survival_kit-master` 

From there I ran system Python using the full path to the binary: `/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 setup.py install` This Installed the script with the System installation of Python and now works with Clarisse 3.6 as well, without modifying its clarisse.env this time.

Of course, I could have used either solution for both versions of Clarisse. Especially, the second solution makes the script work with all the installation of Clarisse because the script is installed with the system version of Python (without having to edit clarisse.env). However, before doing that, I wanted to test the other approach of adding an extra python path to clarisse.env to see if clarisse could use the the system path for its default stuff and the extra path for the script. In fact, this worked.

Thanks again for all your help. That helped me understanding a lot of things. Next I'll have to figure out why Clarisse only works with the system version of python and not with custom installations despite the paths being correctly specified in clarisse.env. However, for now I'm happy with this configuration so I'll be able to enjoy the script.

**Comment by ddesmond** [comment]
@mzogithub Great! Glad to hear that both tricks worked!

I would add to your search for the reasoning around python and env file. Your clarisse.env is setup corectly by iso team. They have pointed to the system one, so it works on any osx probably, cos its the default place to look up. One can use many methods to get python from anaconda to homebrew, i think it would be hard to keep track of all that stuff. you can however change the env file to point to your other python, and try if all gui stuff works and you can access all your libs.

There are indepth anlysis on google around this issue with osx python if you want to dig deeper.

Also, you can only use python 2.7 with clarisse. For reference: https://www.vfxplatform.com/ here you can check what works with Clarisse.

Good luck!

**Comment by mzogithub** [comment]
@ddesmond Thank you for the extra information.
