### ISSUE TITLE
Clarisse doesn't import in the scene

### ISSUE THREAD

**Issue by MichaeLfrh** [aydinyanik/clarisse_survival_kit#17]
Clarisse doesn't import the asset in the scene. I did the install as described. The bridge is reading the port. It import everything to the destenation folder, but it won't import in my project

**Comment by aydinyanik** [comment]
Hi Michael,

Did you enable the Command Port from the Clarisse settings? Do you have a firewall that blocks the communication? Does the Clarisse log show you any errors? 

Kind regards, 

Aydin

**Comment by MichaeLfrh** [comment]
Yes I did. It's enabled. That's the weird thing.

**Comment by aydinyanik** [comment]
Could you join the Clarisse discord server so we can talk/debug your issue easier? It's very easy to setup:

https://discord.gg/he8QTvD

My name is Yanik on that server.
