### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by Refat-Shikder** [aydinyanik/clarisse_survival_kit#30]
I was updated for v5. and icons are showing but not working and log message this
"Traceback (most recent call last)
File "<string>", line 1, in <module>
 ModuleNotFoundError: No module named 'clarisse_survival_kit'"
![image](https://user-images.githubusercontent.com/43178208/138917080-5875aaad-33ed-4872-a84f-d4536ae6b16f.png)

**Comment by aydinyanik** [comment]
Issue closed because according to the Discord chat message you used python3 instead of 2.
